<a href="https://colab.research.google.com/github/mahmoudta74/Pytorch_Tutorial/blob/master/Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor

In [1]:
#import important packages 
import torch
import torchvision
import numpy as np
import matplotlib.pyplot as plt
import torch.nn as nn
import torchvision.transforms as transforms

In [2]:
#create tensor
tensor0d = torch.tensor(5)
tensor1d = torch.tensor([1,2,7])
tensor2d = torch.tensor([[1,2], [4,7]])
#...
print(tensor0d, '\n', tensor1d, '\n', tensor2d, '\n\n\n')

print(tensor2d.shape,'\n',tensor2d.size(), '\n\n\n')    # .size() need () but .shape dose'nt need  
print(tensor2d[0],'\n', tensor2d.shape[0],'\n', tensor2d.size(0), '\n\n\n')



print(tensor2d.dtype)
tensor2d = tensor2d.type(dtype= torch.int32)
print(tensor2d.dtype)
#cpu tensor
tensor2d = tensor2d.type(dtype= torch.FloatTensor)
print(tensor2d.dtype)

#gpu tensor
tensor2d = tensor2d.type(dtype= torch.cuda.FloatTensor)
print(tensor2d.dtype)

tensor(5) 
 tensor([1, 2, 7]) 
 tensor([[1, 2],
        [4, 7]]) 



torch.Size([2, 2]) 
 torch.Size([2, 2]) 



tensor([1, 2]) 
 2 
 2 



torch.int64
torch.int32
torch.float32
torch.float32


torch.Size